import React from "react";

const TermsAndConditions = () => {
  return (
    <div className="container mx-auto px-5 md:px-32 py-8 space-y-6">
      <h1 className="text-3xl font-semibold">Terms & Conditions</h1>
      <p className="text-lg font-medium text-blue-600">www.abacafootwear.com</p>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">Electronic Record:</h2>
        <p className="text-base">
          This document is an electronic record in terms of the Information
          Technology Act, 2000 and rules thereunder as applicable and the
          amended provisions pertaining to electronic records in various
          statutes as amended by the Information Technology Act, 2000. This
          electronic record is generated by a computer system and does not
          require any physical or digital signatures.
        </p>
        <p className="text-base">
          This document is published in accordance with the provisions of Rule 3
          (1) of the Information Technology (Intermediaries Guidelines) Rules,
          2011 which require publishing the rules and regulations, privacy
          policy, and Terms of Use for access or usage of the Website.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">Domain Name:</h2>
        <p className="text-base">
          The domain name www.odyssia.in is owned by ABACA FOOTWEAR - ABACA
          POLYMERS. This Website contains Intellectual Property the use, copy,
          reproduction, publishing, hosting, transmission, or sharing of which
          by User or any third party shall amount to a violation of rights of
          ABACA FOOTWEAR- ABACA POLYMERS.
        </p>
        <p className="text-base">
          License and Operation: The Website is operated i.e. in charge of,
          handled, managed, operated, and run by ABACA POLYMERS.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">Definitions:</h2>
        <p className="text-base">
          For the purpose of the below-mentioned Terms and Conditions of Use of
          this Website and its features, wherever the context so requires:
        </p>
        <ol className="list-decimal pl-6 space-y-2">
          <li>
            <strong>“Additional Terms”</strong> shall mean any terms provided in
            the invoice or on any other documents or illustrations accompanying
            the product.
          </li>
          <li>
            <strong>“Applicable Laws”</strong> shall mean all laws of India,
            ordinances, statutes, rules, orders, decrees, injunctions, licenses,
            permits, approvals, authorizations, consents, waivers, privileges,
            agreements, and regulations of any governmental authority having
            jurisdiction over the relevant matter as such are in effect as of
            the date hereof or as may be amended, modified, enacted or revoked
            from time to time hereafter.
          </li>
          <li>
            <strong>“Intellectual Property”</strong> shall mean trademarks,
            names, pictures, titles, logos, texts, IP addresses, images,
            designs, copyrights, and other proprietary materials owned and
            registered by Euphoric Innovations and licensed to and managed by
            ABACA POLYMERS.
          </li>
          <li>
            <strong>“Policies”</strong> shall mean the Privacy Policy, Legal
            Policy and Disclaimer, and any other policy uploaded onto the
            Website from time to time including any amendments or revisions made
            to existing policies as well as this Terms of Use.
          </li>
          <li>
            <strong>“Terms of Use”</strong> shall mean this Terms and Conditions
            of Use including any amendments or revisions made from time to time.
          </li>
          <li>
            <strong>“ABACA POLYMERS.”</strong> shall mean ABACA POLYMERS. a
            company incorporated under the Companies Act, 2013 having its
            registered office at Odiyssia - ABACA POLYMERS, 11/544-D,
            Mamyalmathil, Kozhikodenkunnu, Olavanna PO, Kozhikode, Kerala-
            673019.
          </li>
          <li>
            <strong>“We”, “Us”, “Our”</strong> shall mean ABACA FOOTWEAR;
          </li>
          <li>
            <strong>“Website”</strong> shall mean ABACA FOOTWEAR.COM and shall
            include the homepage and all other webpages and data files connected
            through hyperlinks excluding any third-party websites on which ABACA
            FOOTWEAR does not have any control;
          </li>
          <li>
            <strong>“You” or “User”</strong> shall mean any natural or legal
            person who has agreed to become a casual user who browses through
            the site, a Registered user/Member who registers by providing
            requisite details, and /or a buyer on the Website.
          </li>
        </ol>
      </section>
      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">Interpretation:</h2>
        <p className="text-base">
          The terms and conditions of the Policies shall apply unless modified
          in the Additional Terms. In the event of any conflict between the
          provisions of the Policies and the Additional Terms, the provisions of
          the Additional Terms shall prevail.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">Applicability:</h2>
        <p className="text-base">
          Your use of the Website and services and tools are governed by the
          following Terms as applicable to the Website including the applicable
          Policies which are referred to herein.
        </p>
        <p className="text-base">
          By mere use of the Website, You shall be contracting with us, these
          Terms including the Policies constitute your binding obligations with
          Us.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">Right to Use and Amendment:</h2>
        <p className="text-base">
          We reserve the right, at Our sole discretion, to change, modify, add,
          or remove portions of these Terms of Use at any time without any prior
          written notice to You.
        </p>
        <p className="text-base">
          It is Your responsibility to review these Terms of Use periodically
          for updates/changes. Your continued use of the Website following the
          posting of changes will mean that You accept and agree to the
          revision.
        </p>
        <p className="text-base">
          As long as You comply with these Terms of Use and other Policies of
          ABACA FOOTWEAR as provided on the Website, We grant You a personal,
          non-exclusive, non-transferable, limited privilege to enter and use
          the Website.
        </p>
        <p className="text-base">
          Throughout this Terms of Use, ABACA FOOTWEAR’S prior written consent
          means a communication coming from ABACA FOOTWEAR, specifically in
          response to Your request, and specifically addressing the activity or
          conduct for which You seek authorization.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">Acceptance:</h2>
        <p className="text-base">
          Browsing or accessing the Website indicates Your agreement to all the
          Terms of Use.
        </p>
        <p className="text-base">
          By impliedly or expressly accepting these Terms of Use, You also
          accept and agree to be bound by Our Policies. Hence, please read the
          Policies carefully before proceeding.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">Eligibility:</h2>
        <p className="text-base">
          Use of the Website for placing online orders is available only to
          persons who can form legally binding contracts under Indian Contract
          Act, 1872.
        </p>
        <p className="text-base">
          Persons who are "incompetent to contract" within the meaning of the
          Indian Contract Act, 1872 including minors (below the age of 18
          years), un-discharged insolvents etc. are not eligible to use the
          Website. If you are incompetent to contract under Indian Contract Act,
          1872 as provided above, you shall not register as a User of the
          Website and shall not transact on or use the Website.
        </p>
        <p className="text-base">
          As a minor if you wish to use or transact on Website, such use or
          transaction may be made by Your legal guardian or parents on the
          Website who agree to be bound by the Terms of Use of the Website and
          responsible for any consequences or implications of a minor using the
          Website without adult supervision.
        </p>
        <p className="text-base">
          We reserve the right to terminate Your membership and / or refuse to
          provide you access to the Website if it is brought to Our notice or if
          it is discovered that you are incompetent to contract under Indian
          Contract Act, 1872 as provided above.
        </p>
      </section>
      <section>
        <div className="space-y-6">
          <p className="font-bold">User Obligations:</p>
          <p>
            You agree to use the Website and the materials provided therein only
            for purposes that are permitted by:
          </p>
          <ul className="list-disc list-inside space-y-2">
            <li>The Terms of Use and other Policies.</li>
            <li>Any Applicable Laws.</li>
            <li>
              You agree to adhere to all limitations on dissemination, use, and
              reproduction of any materials (such as the product catalogues)
              that You access on the Website in accordance with the Policies.
            </li>
            <li>
              You agree not to access (or attempt to access) the Website and the
              materials or services by any means other than through the
              interface that is provided by Us. You shall not use any deep-link,
              robot, spider or other automatic device, program, algorithm or
              methodology, or any similar or equivalent manual process, to
              access, acquire, copy or monitor any portion of the Website or
              Intellectual Property, or in any way reproduce or circumvent the
              navigational structure or presentation of the Website, materials
              or any Content, to obtain or attempt to obtain any materials,
              documents or information through any means not specifically made
              available through the Website. You acknowledge and agree that by
              accessing or using the Website or Services, You may be exposed to
              content from other users that You may consider offensive, indecent
              or otherwise objectionable. ABACA FOOTWEAR disclaims all
              liabilities arising in relation to such offensive content on the
              Website. Further, You may report such offensive content at the
              email address{" "}
              <a
                href="mailto:abacafootwear@gmail.com"
                className="text-blue-500 underline"
              >
                abacafootwear@gmail.com
              </a>
            </li>
          </ul>

          <p className="font-bold">Access to Website:</p>
          <p>
            We will do Our utmost to ensure that availability of the Website
            will be uninterrupted and that transmissions will be error-free.
            However, due to the nature of the internet, this cannot be
            guaranteed. Also, Your access to the Website may also be
            occasionally suspended or restricted to allow for repairs,
            maintenance, or the introduction of new facilities or services at
            any time without prior notice. We will attempt to limit the
            frequency and duration of any such suspension or restriction.
          </p>

          <p className="font-bold">Confidentiality:</p>
          <p>
            As a registered User (member) you are responsible for maintaining
            the confidentiality of user-id and password and you shall be
            responsible for all activities that occur under Your user-id. You
            agree that if You provide any information that is untrue,
            inaccurate, not current or incomplete or if We have reasonable
            grounds to suspect that such information is untrue, inaccurate, not
            current or incomplete, or if not in accordance with the stipulated
            Terms of Use, We shall have the right to indefinitely suspend or
            terminate or block access of Your membership on the Website and
            refuse to provide You with access to the Website.
          </p>

          <p className="font-bold">Communication:</p>
          <p>
            When You use the Website or send emails, information, or
            communication to Us, You understand that You are communicating with
            Us through electronic records and You also consent to receive
            communications via electronic records from Us periodically and as
            and when required.
          </p>

          <p className="font-bold">Price:</p>
          <p>
            Registration / Membership on the Website is free. We do not charge
            for browsing or buying on this Website. The prices of products
            displayed in the Website are the maximum retail price (MRP) only and
            may vary from time to time. Unless otherwise specified, all prices
            mentioned are in Indian Rupees.
          </p>
          <p>
            The prices and products are subject to change from time to time at
            Our discretion. All prices of products displayed on the Website are
            inclusive of applicable taxes. ABACA FOOTWEAR may at its sole
            discretion offer discounts to the customers on their purchases.
          </p>
          <p>
            The Users shall be solely responsible for compliance of all
            Applicable Laws for making payments on orders through the Website.
          </p>
          <p>
            We shall not be responsible for any service charges and related
            taxes levied on You for the use of any payment and settlement
            mechanism or use of any specific bank for facilitating the payment
            and any such additional payments made by You shall be in addition to
            the price paid for purchase of the product.
          </p>
          <p>
            The Website will not facilitate transaction with respect to any
            other form of currency with respect to the purchases made on
            Website. Unless otherwise specified, the products on this Website
            are presented solely for the purpose of sale in India.
          </p>
        </div>
      </section>
      <section>
        <div className="space-y-6">
          <ol className="list-decimal ml-6 space-y-2">
            <li>Requests by law enforcement or other government agencies;</li>
            <li>A request by You (self-initiated account deletions);</li>
            <li>
              Discontinuance or material modification of the Website or any
              service offered on or through the Website; or
            </li>
            <li>Unexpected technical issues or problems.</li>
          </ol>

          <p className="text-gray-700">
            If <span className="font-bold">ABACA FOOTWEAR</span> takes any legal
            action against You as a result of Your violation of these Terms of
            Use, <span className="font-bold">ABACA FOOTWEAR</span> will be
            entitled to recover from You, and You agree to pay, all reasonable
            attorneys’ fees and costs of such action, in addition to any other
            relief granted to <span className="font-bold">ABACA FOOTWEAR</span>.
          </p>

          <p className="font-bold text-lg">Termination:</p>
          <p className="text-gray-700">
            The Terms of Use will continue to apply and survive indefinitely
            until terminated by either You or Us as set forth below.
          </p>
          <p className="text-gray-700">
            If You want to terminate Your agreement with Us, You may do so by:
          </p>

          <ul className="list-disc ml-6 space-y-2">
            <li>Not accessing the Website; or</li>
            <li>
              Closing Your accounts for all of the services that You use, where
              We have made this option available to You on the Website.
            </li>
          </ul>

          <p className="text-gray-700">
            We may, at any time, with or without notice, terminate the Terms of
            Use (or portion thereof) with You if:
          </p>

          <ul className="list-disc ml-6 space-y-2">
            <li>
              You breach any of the provisions of the Terms of Use or any terms
              and conditions of the other Policies that may be applicable to You
              from time to time or have acted in a manner that clearly shows
              that You do not intend to, or are unable to, comply with the same.
            </li>
            <li>
              We are required to do so by Applicable Laws (for example, where
              the provision of services to You is, or becomes, unlawful);
            </li>
            <li>
              The provision of the services to You by Us is, in Our sole
              opinion, no longer commercially viable.
            </li>
            <li>
              We have elected to discontinue, with or without reason, access to
              the Website, the services provided through the Website (or any
              part thereof); or We may also terminate or suspend all or a
              portion of Your account or access to the Website with or without
              reason.
            </li>
          </ul>

          <p className="text-gray-700">
            Except as may be set forth in any Additional Terms applicable to a
            particular product available on the Website, termination of Your
            Account may include:
          </p>

          <ul className="list-disc ml-6 space-y-2">
            <li>Removal of access to all offerings within the Website.</li>
            <li>
              Deletion of Your materials and account information, including Your
              personal information, log-in ID and password, and all related
              information, files, and materials associated with or inside Your
              account (or any part thereof).
            </li>
            <li>Barring of further use of the Website.</li>
          </ul>

          <p className="text-gray-700">
            You agree that all terminations shall be made in Our sole discretion
            and that <span className="font-bold">ABACA FOOTWEAR</span> shall not
            be liable to You or any third party for any termination of Your
            account (and accompanying deletion of Your account information), or
            Your access to the Website and services provided through the
            Website.
          </p>

          <p className="text-gray-700">
            If You or <span className="font-bold">ABACA FOOTWEAR</span>{" "}
            terminates Your use of the Website, We may delete any content or
            other materials relating to Your use of the Website and We will have
            no liability to You or any third party for doing so.
          </p>

          <p className="text-gray-700">
            The termination of this Terms of Use for any reason shall be without
            prejudice to any rights or liabilities of the User or{" "}
            <span className="font-bold">ABACA FOOTWEAR</span> which have accrued
            prior to such termination and shall not affect or prejudice any
            provision of this Terms of Use which expressly or by implication
            comes into effect or continues in effect after termination.
          </p>

          <p className="font-bold text-lg">Limitation of Liability:</p>
          <p className="text-gray-700">
            We will not be responsible for unsatisfactory or delayed performance
            of services or damages or delays as a result of products which are
            out of stock, unavailable, or back-ordered.
          </p>
          <p className="text-gray-700">
            We as a merchant shall be under no liability whatsoever in respect
            of any loss or damage arising directly or indirectly out of the
            decline of authorization for any transaction, on account of having
            exceeded the preset limit mutually agreed by you with the bank or
            any other payment issues arising out of the transaction.
          </p>
        </div>
      </section>
    </div>
  );
};

export default TermsAndConditions;
